### ISSUE TITLE
A way to invert PTZ controls

### ISSUE THREAD

**Issue by thehammer39** [glikely/obs-ptz#102]
Currently, my camera is mounted upside down and the PTZ controls move the camera in the opposite direction.

**Comment by PoWeR-Ding** [comment]
If the image is flipped, then the OBS filter can handle it.
If it is to control the flip, it needs to be updated. .

**Comment by thehammer39** [comment]
I have fixed the image so it shows correctly in OBS. Now when I click the left PTZ button the camera moves to the right.

**Comment by glikely** [comment]
Duplicate of #11
