### ISSUE TITLE
Incorrect filepath for Kubuntu

### ISSUE THREAD

**Issue by Northdiver** [glikely/obs-ptz#107]
Installing the plugin on a Linux Kubuntu distro put shared object file, obs-ptz.so in '/usr/obs-plugins/64bit/'.  It should be in '/usr/lib/x86_64-linux-gnu/obs-plugins/'

**Comment by glikely** [comment]
Thanks for the bug report. I saw that on my machine too. The build scripts are doing a 'portable' build, which is wrong for creating Debian packages.

See: https://github.com/obsproject/obs-plugintemplate/pull/39

I'll update this bug report once I've got it fixed.

**Comment by glikely** [comment]
Fixed in v0.12.0-pre5
