### ISSUE TITLE
OBS 28.0.3 + v0.12.0-pre5-modified

### ISSUE THREAD

**Issue by KariHNN** [glikely/obs-ptz#111]
Always when starting OBS I get a popup 
stating that "ptz-controls failed to load. Update or remove the plugin."

Mostly still that plugin works fine. Sometimes though when I have shut down power from computer and restarted the plugin has really failed to load with no settings at all remaining (like Visca over IP camera)

Is there something you recommend me to check or do?

**Comment by glikely** [comment]
It sounds like you still have an older version of the plugin alongside v0.12.0-pre5. Go into the plugins directory and delete the ptz-controls.* files

**Comment by KariHNN** [comment]
And right you were. Thank you!
