### ISSUE TITLE
ptz-controls fails to load in OBS

### ISSUE THREAD

**Issue by AmyGM** [glikely/obs-ptz#115]
Two days ago I updated OBS to the latest version and this morning updated to the most recent PTZ Controls v.0.12.1. When I start up OBS, it says the plug in failed to load.
Here's the log.
https://obsproject.com/logs/0RRn10N5OMAkNJXI
I'm going to be in a bind for our worship stream tomorrow if I can't get this figured out. I guess a solution is to return to previous versions of OBS and PTZ controls, but I was updating in order to work out bugs (random unset PTZ views showing up during livestreams). Do I need to set up an entirely new OBS profile and start over on everything?

In the future, if we have the random view problem, I will know how to find the log, but at this point that log is long gone, it seems.

**Comment by glikely** [comment]
The log file shows that obs-ptz.dll has loaded fine and it is talking to your cameras! v0.12.1 appears to be working.

It also shows that ptz-controls.dll failed to load, which is the filename of the older version of the plugin. Delete ptz-controls.dll from the plugins directory and the error message should go away.
