### ISSUE TITLE
INVERT CONTROL PTZ

### ISSUE THREAD

**Issue by arturarruda** [glikely/obs-ptz#117]
In my application I use the camera upside down. On the camera configuration site I can change image and PTZ PTZ Controte. But during use in OBS the controls A are reversed both horizontal and vertical. There is some way to change this configuration

**Comment by glikely** [comment]
Hi arturarruda. This is something on the todo list, but I haven’t gotten around to it yet. Hopefully soon.

Duplicate of #11
