### ISSUE TITLE
Save control dock size and position

### ISSUE THREAD

**Issue by JanGVH** [glikely/obs-ptz#120]
I scale the camera control UI to a certain spot on my screen.
I would like it if it came back there when reopening the plugin.

**Comment by glikely** [comment]
Can you provide more details please? What platform are you running on. Save & restore of window position works fine for me on MacOS

**Comment by playaspec** [comment]
I encountered a similar issue with two other plugins. I'd set them up, even locking the docks, quit, reopen OBS, and they'd be reset. I was about to open an issue with each plugin's author, when I read a comment on a closed issue suggesting to set up plugin docks as desired, take OBS out of full screen, then quit and reload.

Wouldn't ya know, it fixed the problem! Some weird bug with OBS itself not remembering dock positions while maximized to full screen. Once the preference was written, OBS started maximized with all docks where they should be.

Anyone running across this, let us know here if it fixed similar.

**Comment by glikely** [comment]
Sounds like this is resolved. Closing the issue.
