### ISSUE TITLE
Movement Speed Controls for Camera

### ISSUE THREAD

**Issue by rasamassen** [glikely/obs-ptz#122]
Since the release of v0.13.0 with no speed slider but increased speed the longer you press a button, we're having problems. It's not working. Our PTZOptics NDI camera goes from 0 to 60 in 1.5 seconds, and if you hold for 1.5 seconds, the camera is moving so fast that when you release it keeps moving for another second. But holding shift results in such a snail pace it would take you 20 seconds to move 30 degrees.

Options:
1) Ability to revert to previous style if desired, in settings - the speed slider worked for us (though I agree that design-wise, no speed slider makes sense; it's cleaner)
2) Ability to set max speed - it's going to be rare, in our setting at least, to want to move at the camera's max speed, so holding down the arrows shouldn't speed up to faster than a comfortable pan.
3) Ability to set "shift" speed, which right now is snail pace - if shift always went at the desired pan speed, that would work (though it would make it hard to make micro adjustments)

Not sure the right answer, but the controls have become unwieldy with this revision.

**Comment by glikely** [comment]
Ability to set a max speed has now been implemented and is in mainline, and it will be available in the next release.
