### ISSUE TITLE
PTZ Action - Save presets in PTZ Action menu

### ISSUE THREAD

**Issue by ClaudeQc** [glikely/obs-ptz#134]
For some reason, in the PTZ Action in sources of OBS :
In the action selection, we have Preset, Pan/Tilt and Stop but not Save ?

I'm on windows 11 with OBS 29.0.0

**Comment by glikely** [comment]
You just happen to be the first person to ask for this! I'm get it added.

**Comment by ClaudeQc** [comment]
Thank's, it's for crating Scene called on my StreamDeck.
