### ISSUE TITLE
Missing Presets at PTZ Action

### ISSUE THREAD

**Issue by arteVact** [glikely/obs-ptz#136]
I suddenly can't recall a preset under PTZ Action/Preset Recall. What am I doing wrong?

**Comment by glikely** [comment]
Yeah, I discovered that bug after releasing. I'm working on a fix. As a workaround, just rename the preset and it will appear in the list again.

**Comment by arteVact** [comment]
Thank you for the tip. You do an incredibly good job, that cannot be emphasised enough. Great!

 
 

Gesendet: Freitag, 10. Februar 2023 um 13:08 Uhr
Von: "Grant Likely" ***@***.***>
An: "glikely/obs-ptz" ***@***.***>
Cc: "arteVact" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [glikely/obs-ptz] Missing Presets at PTZ Action (Issue #136)


 

Yeah, I discovered that bug after releasing. I'm working on a fix. As a workaround, just rename the preset and it will appear in the list again.
