### ISSUE TITLE
Camera slowly zooms out

### ISSUE THREAD

**Issue by ritchiedc** [glikely/obs-ptz#140]
I tried your joystick update and found that the camera would slowly zoom out once I started a move, even from the screen buttons. This occurred whether the joystick was enabled or not and I restarted obs. I had to revert to v14.1

**Comment by glikely** [comment]
Thanks for the bug report. I already found an issue with joysticks that don’t center to 0, but this is the first I heard of drift problems even when support is disabled. I’ll investigate

**Comment by ritchiedc** [comment]
Let me know if you need any more info

**Comment by glikely** [comment]
Please try v0.15.2 and report back

**Comment by ritchiedc** [comment]
I won't be able to try it until Wednesday but I'll report back. Thank you for your work on this.
