### ISSUE TITLE
Logitech PTZ Pro 2 with USB connection

### ISSUE THREAD

**Issue by JohnArduini** [glikely/obs-ptz#153]
I have a Windows 10 PC with a PTZ Pro 2 connected via a USB 3.  The plugin is exactly what I would like but it seems the plugin only works with "network" connected cameras.  IS there a way to use this plugin with USB connected cameras or is it something that can be added as a future enhancement or??  Thanks.   .... John

**Comment by glikely** [comment]
Sorry, USB UVC cameras like that one are not supported yet

**Comment by glikely** [comment]
Duplicate of #71
