### ISSUE TITLE
Map Camera Presets to Scenes

### ISSUE THREAD

**Issue by devinbost** [glikely/obs-ptz#179]
I'd love to find a way to map camera presets to scenes so that switching scenes would automatically switch between camera presets. 
Can anyone think of a way this could be done?

**Comment by dleffler** [comment]
In the sources for a Scene, add a 'PTZ Action' and set the Action to Preset Recall, and select which preset to recall.  I have all my scenes set up this way.

**Comment by devinbost** [comment]
This works amazingly well! Thank you so much!
