### ISSUE TITLE
PTZ Controls not loading

### ISSUE THREAD

**Issue by atscomms** [glikely/obs-ptz#25]
I copied the 4 files from the Zip to the plugins/64bit folder and relaunched OBS. I don't see any PTZ control options in the View or View Docks menu.
Here's the OBS Log

16:33:47.505: CPU Name: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
16:33:47.505: CPU Speed: 2712MHz
16:33:47.505: Physical Cores: 2, Logical Cores: 4
16:33:47.505: Physical Memory: 8096MB Total, 4039MB Free
16:33:47.505: Windows Version: 10.0 Build 19042 (release: 2009; revision: 1083; 64-bit)
16:33:47.505: Running as administrator: false
16:33:47.505: Aero is Enabled (Aero is always on for windows 8 and above)
16:33:47.506: Windows 10 Gaming Features:
16:33:47.506: 	Game Bar: Off
16:33:47.506: 	Game DVR: Off
16:33:47.506: 	Game DVR Background Recording: Off
16:33:47.509: Sec. Software Status:
16:33:47.514: 	Webroot SecureAnywhere: enabled (AV)
16:33:47.514: 	Microsoft Defender Antivirus: disabled (AV)
16:33:47.514: 	Windows Firewall: enabled (FW)
16:33:47.515: Current Date/Time: 2021-07-15, 16:33:47
16:33:47.515: Browser Hardware Acceleration: true
16:33:47.515: Portable mode: false
16:33:47.915: OBS 27.0.1 (64-bit, windows)
16:33:47.915: ---------------------------------
16:33:47.945: ---------------------------------
16:33:47.945: audio settings reset:
16:33:47.945: 	samples per sec: 48000
16:33:47.945: 	speakers:        2
16:33:47.946: ---------------------------------
16:33:47.946: Initializing D3D11...
16:33:47.946: Available Video Adapters: 
16:33:47.949: 	Adapter 0: Intel(R) HD Graphics 620
16:33:47.949: 	  Dedicated VRAM: 134217728
16:33:47.949: 	  Shared VRAM:    4244981760
16:33:47.949: 	  PCI ID:         8086:5916
16:33:47.950: 	  Driver Version: 23.20.16.4973
16:33:47.950: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=60, name=
16:33:47.953: Loading up D3D11 on adapter Intel(R) HD Graphics 620 (0)
16:33:47.973: D3D11 loaded successfully, feature level used: b000
16:33:47.973: DXGI increase maximum frame latency success
16:33:48.497: ---------------------------------
16:33:48.497: video settings reset:
16:33:48.497: 	base resolution:   1920x1080
16:33:48.497: 	output resolution: 1920x1080
16:33:48.497: 	downscale filter:  Bicubic
16:33:48.497: 	fps:               30/1
16:33:48.497: 	format:            NV12
16:33:48.497: 	YUV mode:          709/Partial
16:33:48.497: NV12 texture support not available
16:33:48.498: Audio monitoring device:
16:33:48.498: 	name: Speakers (CEntrance MicPort Pro)
16:33:48.498: 	id: {0.0.0.00000000}.{274ab247-0b7e-4c70-bb82-05efc92b7e8e}
16:33:48.502: ---------------------------------
16:33:48.503: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin
16:33:48.505: Skipping module '../../obs-plugins/64bit/concrt140.dll', not an OBS plugin
16:33:48.509: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
16:33:48.510: Failed to load 'en-US' text for module: 'decklink-captions.dll'
16:33:48.512: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
16:33:48.978: [AMF] Unable to load 'amfrt64.dll', error code 126.
16:33:48.982: [AMF] AMF Test failed due to one or more errors.
16:33:48.982: Failed to initialize module 'enc-amf.dll'
16:33:48.997: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
16:33:49.008: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
16:33:49.009: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
16:33:49.015: Skipping module '../../obs-plugins/64bit/msvcp140.dll', not an OBS plugin
16:33:49.018: [obs-browser]: Version 2.14.3
16:33:49.018: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100
16:33:49.024: [noise suppress: Nvidia RTX denoiser disabled, redistributable not found]
16:33:49.026: [obs-ndi] hello ! (version 4.9.0)
16:33:49.026: [obs-ndi] Trying 'C:\Program Files\NewTek\NDI 4 Runtime\v4'
16:33:49.027: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NDI 4 Runtime/v4/Processing.NDI.Lib.x64.dll'
16:33:49.032: [obs-ndi] NDI runtime loaded successfully
16:33:49.044: [obs-ndi] NDI library initialized successfully (NDI SDK WIN64 06:20:19 Apr  1 2020 4.5.1.0)
16:33:49.087: Skipping module '../../obs-plugins/64bit/Qt5Network.dll', not an OBS plugin
16:33:49.089: Module '../../obs-plugins/64bit/Qt5Network.dll' not loaded
16:33:49.093: [Source Dock] loaded version 0.1.1
16:33:49.095: Failed to load 'en-US' text for module: 'StreamDeckPlugin.dll'
16:33:49.106: Skipping module '../../obs-plugins/64bit/ucrtbase.dll', not an OBS plugin
16:33:49.107: Skipping module '../../obs-plugins/64bit/vccorlib140.dll', not an OBS plugin
16:33:49.109: Skipping module '../../obs-plugins/64bit/vcruntime140.dll', not an OBS plugin
16:33:49.114: VLC found, VLC video source enabled
16:33:49.124: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
16:33:49.126: No blackmagic support
16:33:49.139: ---------------------------------
16:33:49.139:   Loaded Modules:
16:33:49.139:     win-wasapi.dll
16:33:49.139:     win-mf.dll
16:33:49.139:     win-dshow.dll
16:33:49.139:     win-decklink.dll
16:33:49.139:     win-capture.dll
16:33:49.139:     vlc-video.dll
16:33:49.139:     text-freetype2.dll
16:33:49.139:     StreamDeckPlugin.dll
16:33:49.139:     source-dock.dll
16:33:49.139:     rtmp-services.dll
16:33:49.139:     obs-x264.dll
16:33:49.139:     obs-vst.dll
16:33:49.139:     obs-transitions.dll
16:33:49.139:     obs-text.dll
16:33:49.139:     obs-qsv11.dll
16:33:49.139:     obs-outputs.dll
16:33:49.139:     obs-ndi.dll
16:33:49.139:     obs-filters.dll
16:33:49.139:     obs-ffmpeg.dll
16:33:49.139:     obs-browser.dll
16:33:49.139:     image-source.dll
16:33:49.139:     frontend-tools.dll
16:33:49.139:     enc-amf.dll
16:33:49.139:     decklink-ouput-ui.dll
16:33:49.139:     decklink-captions.dll
16:33:49.139:     coreaudio-encoder.dll
16:33:49.139: ---------------------------------
16:33:49.140: ==== Startup complete ===============================================
16:33:49.179: Switched to Preview/Program mode
16:33:49.179: ------------------------------------------------
16:33:49.187: All scene data cleared
16:33:49.187: ------------------------------------------------
16:33:49.238: [WASAPISource::WASAPISource] Device '{0.0.0.00000000}.{800788e8-e5ba-4681-9b45-3f8da1978cbf}' not found.  Waiting for device
16:33:49.239: [Loaded global audio device]: 'Desktop Audio'
16:33:49.240: [WASAPISource::WASAPISource] Device '{0.0.1.00000000}.{8464afd4-7a46-498f-b0ab-02d7672486cc}' not found.  Waiting for device
16:33:49.240: [Loaded global audio device]: 'Mic/Aux'
16:33:49.240:     - filter: 'Compressor' (compressor_filter)
16:33:49.240:     - filter: 'Expander' (expander_filter)
16:33:49.249: [obs-ndi] started A/V threads for source 'HP-LAPTOP (AMD Radeon HD 6470M 1)'
16:33:49.251: [obs-ndi] A/V thread for 'NDI™ Source' started
16:33:49.295: Switched to scene 'Cam 2 PTZ'
16:33:49.353: ------------------------------------------------
16:33:49.353: Loaded scenes:
16:33:49.353: - scene 'Cam 1 Fixed':
16:33:49.353:     - source: 'Fixed Cam' (dshow_input)
16:33:49.353: - scene 'Cam 2 PTZ':
16:33:49.353:     - source: 'PTZ Cam' (dshow_input)
16:33:49.353: - scene 'NDI Scene':
16:33:49.353:     - source: 'NDI™ Source' (ndi_source)
16:33:49.353: ------------------------------------------------
16:33:49.458: Fixed Cam: data.GetDevice failed
16:33:49.458: Fixed Cam: Video configuration failed
16:33:49.492: ---------------------------------
16:33:49.492: [DShow Device: 'PTZ Cam'] settings updated: 
16:33:49.492: 	video device: MEI CV610-U3-V2
16:33:49.492: 	video path: \\?\usb#vid_2cb3&pid_0201&mi_00#7&e990382&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
16:33:49.492: 	resolution: 1280x720
16:33:49.492: 	flip: 0
16:33:49.492: 	fps: 30.00 (interval: 333333)
16:33:49.492: 	format: YUY2
16:33:49.808: 	using video device audio: no
16:33:49.808: 	audio device: Digital Audio Interface (MEI CV610-U3-V2)
16:33:49.808: 	sample rate: 44100
16:33:49.808: 	channels: 2
16:33:49.808: 	audio type: Capture
16:36:48.974: adding 640 milliseconds of audio buffering, total audio buffering is now 640 milliseconds (source: PTZ Cam)
16:36:48.974:

**Comment by glikely** [comment]
From discussion on OBS forum, plugin was copied into wrong directory. Moving location solved problem.

https://obsproject.com/forum/threads/ptz-controls.143676/post-535336
