### ISSUE TITLE
gamepad doesn't work on windows

### ISSUE THREAD

**Issue by dattrax** [glikely/obs-ptz#4]
Gamepad wasn't detected on windows.

patch for fix attached

[0001-workaround-for-gamepads-on-windows.zip](https://github.com/glikely/obs-ptz/files/6618886/0001-workaround-for-gamepads-on-windows.zip)

**Comment by glikely** [comment]
I'm still not able to get gamepads to work on my system, but all the devices I have here only work with DirectInput and QGamepad requires the XInput backend. I've got an Xbox controller on order and I can try again once that arrives.

In the mean time I would like merge the patch, but I want two things from you: to have the patch in the form of a GitHub pull request, and for the commit description to include a DCO* "Signed-off-by:" line to confirm that you're contributing the patch under the project license (GPLv2) and to give proper attribution.

*DCO is the Developer Certificate of Origin process used by the Linux kernel and described here: https://developercertificate.org/. If what is in the DCO statement is true, then add a "Signed-off-by: [Your name] <youremail@domain.com>" line to the commit description.
