### ISSUE TITLE
Can't control Cisco PrecisionHD 12x

### ISSUE THREAD

**Issue by KickASS0r** [glikely/obs-ptz#64]
Hi there,

i've tried to control my Cisco PrecisionHD 12x with the VISCA-Serial option.
Had anyone luck doing this? Do i need a special cable?

Kind Regards

**Comment by glikely** [comment]
The plugin does support Cisco PrecisionHD cameras. I believe you need to use a serial connection between the PC and the camera. See the camera manual for details on how the serial port is wired up. You'll need a USB to RS232 adapter and you'll need to build or buy an RS232 to RJ45 adapter cable.

Also see this issue where getting the Cisco camera working was discussed: https://github.com/glikely/obs-ptz/issues/19
