### ISSUE TITLE
Request: Speed Ramping

### ISSUE THREAD

**Issue by EaB11** [glikely/obs-ptz#65]
it would be good to have speed ramping controls to avoid the jerky movement of many PTZ cameras...  so movement could begin slow and then within a second or two increases to the maximum speed..  this would help PTZ movement to be used within the production more, rather than just a way of changing between static shots... 

ideally it would be good to have independent controls for each axis (pan/tilt and zoom).. for example you might want slower speeds for pan/tilt controls but prefer zoom speed a bit faster.. 

also an option to have the ramp settings apply only when the camera is the active output but then have separate speed controls for repositioning when not the active camera..  you generally want preview reposition to happen quickly and the smoother ramping for when camera is active... 

finally it would be good if ramp settings were able to be set individually for each camera.. that way if you had different PTZ models that behaved slightly different they could be calibrated to match..

**Comment by arteVact** [comment]
That would be really fantastic. A real reduction in workload and productions would become much more professional!

**Comment by glikely** [comment]
Please try out v0.13.0-test2. It implements speed ramping

**Comment by arteVact** [comment]
Awesome, thanks a lot!!!
