### ISSUE TITLE
The menu of "Power off" does not show exactly

### ISSUE THREAD

**Issue by iesv** [glikely/obs-ptz#72]
When the camera is powered on, it starts automatically. When I want to turn it off, but the power menu does not show the off option, it still shows on.

**Comment by norihiro** [comment]
How about just showing both `Power On` and `Power Off`?

**Comment by iesvme** [comment]
> How about just showing both `Power On` and `Power Off`?

This is a good suggestion. It would be better to show both on and off at the same time.

**Comment by glikely** [comment]
Please try v0.13.0-test2. Should be fixed now

**Comment by markusd1984** [comment]
> Please try v0.13.0-test2. Should be fixed now

I'm using v0.15.3 with VISCA/TCP and only get `PowerOn` displayed, no option to turn it off.
