### ISSUE TITLE
PTZ Controls v0.10.4 Mac

### ISSUE THREAD

**Issue by strabinsky** [glikely/obs-ptz#76]
Hi,

PTZ controls v0.10.4 doesn't show up in Dock menu of OBS 26.0.2.
I hope you can make it work!

Grtz,

Igor.

**Comment by glikely** [comment]
How did you install the plugin? Are you using a prebuilt version of obs-studio, or are you building it from source?
Please attach a copy of your obs log file so I can see if the plugin is getting loaded
