### ISSUE TITLE
Linux - Buttons are too big

### ISSUE THREAD

**Issue by maxdrfr** [glikely/obs-ptz#8]
I don't know if it's the same on Windows, but on Linux, the pad is too big.
How to adjust the size?

Thanks for your help!

![Capture du 2021-06-17 01-15-53](https://user-images.githubusercontent.com/17526713/122307105-fa8afc80-cf09-11eb-9652-ffc874492d2d.png)

**Comment by glikely** [comment]
Please try v0.5.0 and let me know if the button size is better for you

**Comment by maxdrfr** [comment]
Thats better, the buttons fits.
Thank you.
