### ISSUE TITLE
Feature request: Vaddio Telnet support

### ISSUE THREAD

**Issue by coalhot** [glikely/obs-ptz#80]
Hi!
Would love to see support for the Vaddio Telnet protocol in this plugin! Please let me know if there's information I could get having hardware that would help with this.

Thanks!
--Phil

**Comment by glikely** [comment]
Can you point me at technical details of the vaddio protocol? What hardware uses this protocol?

**Comment by glikely** [comment]
Closing due to lack of information or access to hardware
