### ISSUE TITLE
Trouble with Mac install

### ISSUE THREAD

**Issue by nradina** [glikely/obs-ptz#85]
Hello--

I'm sure this is user error, so I apologize for my newbie troubles. 
I cloned the directory following the macos terminal instructions, although receiving "bash no such file or directory" when following the build instructions.

CI/macos/macos-build.sh
CI/macos/macos-package.sh

result:
-bash: .CI/macos/macos-package.sh: No such file or directory

Thanks for any help!

**Comment by norihiro** [comment]
> -bash: .CI/macos/macos-package.sh
A slash `/` between `.` and `C` is missing.
That command should be
```
./CI/macos/macos-package.sh
```
