### ISSUE TITLE
Configure more than 16 presets?

### ISSUE THREAD

**Issue by nicolasvivant** [glikely/obs-ptz#86]
Hello,

The number of presets seems to be limited to 16. I didn't find a way to increase it.
Is it possible?

Thanks for your help!

**Comment by allegfede** [comment]
Got the same request.
Could be usefull to add and remove from the preset list the ones not used or add more than the original 16.

**Comment by splaestro** [comment]
Amen, amen! We use PTZOptics cameras, which will allow for 256 presets... I don't think anyone needs _that_ many, but one of our cameras does have 20+ at present.

**Comment by arek-pelski** [comment]
This would be very useful and convenient. I join in the request.

**Comment by rasamassen** [comment]
Agreed. It should be easy to add/delete presets (when adding, it automatically picks the next open number) so that each camera only shows the number of presets we're actually using.

**Comment by AnthonyG83** [comment]
I would like to see the ability to add more presets.

Thanks.

**Comment by ClaudeQc** [comment]
Happy new Year,

I request more than 50 preset yoo if you can. And more Store preset in shotrt cut preference not only recall preset.

Thank's
![Capture](https://user-images.githubusercontent.com/121186634/210439516-4ba1aa0f-c5fe-4f95-bb46-17ece36b0a5b.JPG)

**Comment by glikely** [comment]
I've made the number of presets configurable and closed this issue. @ClaudeQc Please open another issue to request Memory Store shortcuts be added

**Comment by nicolasvivant** [comment]
Thanks a lot!
