### ISSUE TITLE
Uninstall procedure on Mac

### ISSUE THREAD

**Issue by andreaquaglio** [glikely/obs-ptz#87]
Is it available an uninstall procedure to remove it in MacOS?

**Comment by andreaquaglio** [comment]
I installed this one: https://github.com/glikely/obs-ptz/releases/tag/v0.10.2

**Comment by wykananda** [comment]
On MacOS, typically you'll find OBS Studio plugin files in here: /Library/Application Support/obs-studio/plugins . Throwing out file(s)/folder(s) that start with "obs-ptz" should remove the plugin from OBS Studio.

**Comment by glikely** [comment]
As @wykananda says, removing the plugin from `/library/Application Support/obs-studio/plugins` should do the trick.
