### ISSUE TITLE
PTZ Action missing under sources

### ISSUE THREAD

**Issue by smcaylor75** [glikely/obs-ptz#88]
Is there a procedure to repopulate the PTZ Action in the Sources Dock within OBS?  I have had inconsistent behavior in getting that to appear.  Any help is appreciated.

**Comment by glikely** [comment]
I've not seen that behaviour myself. Can you elaborate please, and attach log files from both working and non-working runs?

**Comment by glikely** [comment]
Closing due to lack of information
