### ISSUE TITLE
Vaddio RoboSHOT Support

### ISSUE THREAD

**Issue by BrokenShovel** [glikely/obs-ptz#90]
PTZ Controls v0.10.4 has some operations issues with Vaddio RoboSHOT PTZ cameras.  According to the camera manufacture's literature, Vaddio uses a modified set of Sony VISCA commands (see attached user manual page 81).   My experience has been that if I have more than one Vaddio RoboSHOT camera assigned to the PTZ Controls PTZ Devices, then the PTZ Controls become unresponsive.   This also has the effect of making the camera's built-in web browser movement controls and telnet movement controls unresponsive.  I found that by simply closing PTZ controls the cameras remained unresponsive in the web browser.  It wasn't until I deleted the cameras from the PTZ devices and closed the PTZ controls did the cameras start to respond.  The cameras have diagnostic reporting but nothing gets reported until after the cameras become unresponsive (ie the second command sent triggers the error message).  So those are my observations.  I'm not a programmer but happy to help in other ways.  I found the RoboSHOT user manual has all of the VISCA commands.   Would it be possible to make PTZ control compatible with Vaddio cameras?  I'd be happy to do the legwork to copy that list of VISCA commands into a text file if someone could post the column headers.  

One other thing I found strange was the properties displayed for the PTZ devices.  I have four identical RoboSHOTs and each one had a different set of visible properties displayed, things like settings, parameters and such. Almost like some mis-match in what the PTZ controls was expecting from the camera.   Like I said, not a programmer but let me know what sort of information would be helpful and I'll try to find it.  Thanks!!!!

**User Manual**
[411-0003-30-rev-f-roboshot-hdbt-complete-manual.pdf](https://github.com/glikely/obs-ptz/files/8422456/411-0003-30-rev-f-roboshot-hdbt-complete-manual.pdf)

**Manufacture's Website**
https://www.legrandav.com/products/cameras/discontinued/roboshot-12-hdbt/999-9960-000#sort=relevancy&numberOfResults=20

**Comment by glikely** [comment]
Please try again with release v0.15.2. I've made a lot of improvements to the plugin over the last year and fixed a number of protocol bugs. Reopen this issue if you are still having problems.
