### ISSUE TITLE
Gamepad

### ISSUE THREAD

**Issue by arteVact** [glikely/obs-ptz#99]
I have a PS3/Xbox controller that gives me good control of my Newtek PTZ cameras via the NDI monitor. But when I activate "enable gamepad" in OBS nothing happens. Is it the gamepad, the cameras, or do I need to do something extra?

**Comment by twalp** [comment]
I have the same question. Please reply to this thread if you find a solution.

**Comment by glikely** [comment]
Gamepad support is broken and will be removed in the next official release

**Comment by mudnug** [comment]
Good news: https://github.com/glikely/obs-ptz/pull/118

**Comment by glikely** [comment]
Please give v0.15.0 a try. Joystick support is now included.

https://github.com/glikely/obs-ptz/releases/v0.15.0
